# Generated by Django 4.1.4 on 2023-01-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'HOD'), (2, 'Agent'), (3, 'Customer')], default=1, max_length=10),
        ),
    ]
